# Site Settings
name: manazrasidi
title: manazrasidi
email: manaz@mailbox.org
description:
baseurl: /
url: /
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
excerpt_separator: <!--more-->
plugins: [jekyll-paginate]
paginate: 6
paginate_path: /page:num/
